spring.application.name=telemetry-analyzer
server.port=8080

spring.datasource.url=jdbc:postgresql://host.docker.internal:5433/telemetry_analyzer
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect